###
#
# cd_linux_prod.yml
#
# Config data for linux client connecting to the Production environment
#
###

esprit_client: '/opt/GShareForEspritGames/gshare-for-esprit'
gamecredits_client: '/opt/GShare/gshare-app'
