###
#
# cd_windows_stage.yml
#
# Config data for windows client connecting to the Staging environment
#
###

esprit_client: 'C:\\Users\\daxazord\\AppData\\Local\\Programs\\gshare-for-esprit\\GShareForEspritGames.exe'
gamecredits_client: 'C:\Users\daxazord\AppData\Local\Programs\gshare-app\GShare.exe'
