###
#
# cd_windows_prod.yml
#
# Config data for windows client connecting to the Production environment
#
###

esprit_client: 'C:\Program Files\GameCredits\GShareForEspritGames\0.9\GShareForEspritGames.exe'
gamecredits_client: 'C:\Program Files\GameCredits\GShare\0.9\GShare.exe'
