###
#
# cd_windows_stage.yml
#
# Config data for windows client connecting to the Staging environment
#
###

<<<<<<< HEAD
esprit_client: 'C:\\Users\\babic\\AppData\\Local\\Programs\\gshare-for-esprit\\GShareForEspritGames.exe'
gamecredits_client: 'C:\Users\babic\AppData\Local\Programs\gshare-app\GShare.exe'
=======
esprit_client: 'C:\\Users\\milan\\AppData\\Local\\Programs\\gshare-for-esprit\\GShareForEspritGames.exe'
gamecredits_client: 'C:\Users\milan\AppData\Local\Programs\gshare-app\GShare.exe'
>>>>>>> develop
